<?xml version="1.0" encoding="utf-8"?><Database Name="BTS" Class="BTSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ROMINA-VAIO\SQL2019;Initial Catalog=BTS;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="BTSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Backup]" Member="Backup">
    <Type Name="Backup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreArchivo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Destino" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Origen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bitacora" Member="Bitacora">
    <Type Name="Bitacora">
      <Column Name="IdBitacora" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TipoEvento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntidadInvolucrada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="CodCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DomicilioEntrega" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DomicilioFact" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dni" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cliente_Factura" Member="Factura" ThisKey="CodCliente" OtherKey="CodCliente" Type="Factura" />
      <Association Name="Cliente_NotaDePedido" Member="NotaDePedido" ThisKey="CodCliente" OtherKey="CodCliente" Type="NotaDePedido" />
      <Association Name="Cliente_Recibo" Member="Recibo" ThisKey="CodCliente" OtherKey="CodCliente" Type="Recibo" />
    </Type>
  </Table>
  <Table Name="dbo.ControlSistema" Member="ControlSistema">
    <Type Name="ControlSistema">
      <Column Name="IdControl" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreControl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UbicacionControl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ControlSistema_Traduccion" Member="Traduccion" ThisKey="IdControl" OtherKey="IdControl" Type="Traduccion" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RazonSocial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cuit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Factura" Member="Factura">
    <Type Name="Factura">
      <Column Name="NroFactura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CodCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NroPedido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Factura_Recibo" Member="Recibo" ThisKey="NroFactura" OtherKey="NroFactura" Type="Recibo" />
      <Association Name="Factura_Remito" Member="Remito" ThisKey="NroFactura" OtherKey="NroFactura" Type="Remito" />
      <Association Name="Cliente_Factura" Member="Cliente" ThisKey="CodCliente" OtherKey="CodCliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="NotaDePedido_Factura" Member="NotaDePedido" ThisKey="NroPedido" OtherKey="NroPedido" Type="NotaDePedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Idioma" Member="Idioma">
    <Type Name="Idioma">
      <Column Name="IdIdioma" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Idioma_Traduccion" Member="Traduccion" ThisKey="IdIdioma" OtherKey="IdIdioma" Type="Traduccion" />
      <Association Name="Idioma_Usuario" Member="Usuario" ThisKey="IdIdioma" OtherKey="IdIdioma" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Marca" Member="Marca">
    <Type Name="Marca">
      <Column Name="IdMarca" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Marca_OrdenCompra" Member="OrdenCompra" ThisKey="IdMarca" OtherKey="IdMarca" Type="OrdenCompra" />
      <Association Name="Marca_Producto" Member="Producto" ThisKey="IdMarca" OtherKey="IdMarca" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Modelo" Member="Modelo">
    <Type Name="Modelo">
      <Column Name="IdModelo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Modelo_OrdenCompra" Member="OrdenCompra" ThisKey="IdModelo" OtherKey="IdModelo" Type="OrdenCompra" />
      <Association Name="Modelo_Producto" Member="Producto" ThisKey="IdModelo" OtherKey="IdModelo" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.NotaDePedido" Member="NotaDePedido">
    <Type Name="NotaDePedido">
      <Column Name="NroPedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrecioTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoOperacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PeriodoAlquiler" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NotaDePedido_Factura" Member="Factura" ThisKey="NroPedido" OtherKey="NroPedido" Type="Factura" />
      <Association Name="NotaDePedido_ProductosxNP" Member="ProductosxNP" ThisKey="NroPedido" OtherKey="NroPedido" Type="ProductosxNP" />
      <Association Name="NotaDePedido_Remito" Member="Remito" ThisKey="NroPedido" OtherKey="NroPedido" Type="Remito" />
      <Association Name="Cliente_NotaDePedido" Member="Cliente" ThisKey="CodCliente" OtherKey="CodCliente" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdenCompra" Member="OrdenCompra">
    <Type Name="OrdenCompra">
      <Column Name="NroOrdenCompra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodProveedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TipoInstrumento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdMarca" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdModelo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="OrdenCompra_OrdenPago" Member="OrdenPago" ThisKey="NroOrdenCompra" OtherKey="NroOrdenCompra" Type="OrdenPago" />
      <Association Name="OrdenCompra_ProductosxOC" Member="ProductosxOC" ThisKey="NroOrdenCompra" OtherKey="NroOrdenCompra" Type="ProductosxOC" />
      <Association Name="Marca_OrdenCompra" Member="Marca" ThisKey="IdMarca" OtherKey="IdMarca" Type="Marca" IsForeignKey="true" />
      <Association Name="Modelo_OrdenCompra" Member="Modelo" ThisKey="IdModelo" OtherKey="IdModelo" Type="Modelo" IsForeignKey="true" />
      <Association Name="Proveedor_OrdenCompra" Member="Proveedor" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdenPago" Member="OrdenPago">
    <Type Name="OrdenPago">
      <Column Name="NroOrdenPago" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaFactProv" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NroFactProv" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DetalleFactura" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CondicionPago" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NroOrdenCompra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodProveedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OrdenPago_OrdenPago" Member="OrdenPago2" ThisKey="NroOrdenPago" OtherKey="NroOrdenPago" Type="OrdenPago" Cardinality="One" />
      <Association Name="OrdenCompra_OrdenPago" Member="OrdenCompra" ThisKey="NroOrdenCompra" OtherKey="NroOrdenCompra" Type="OrdenCompra" IsForeignKey="true" />
      <Association Name="OrdenPago_OrdenPago" Member="OrdenPago1" ThisKey="NroOrdenPago" OtherKey="NroOrdenPago" Type="OrdenPago" IsForeignKey="true" />
      <Association Name="Proveedor_OrdenPago" Member="Proveedor" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permiso" Member="Permiso">
    <Type Name="Permiso">
      <Column Name="IdPermiso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoPermiso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Permiso_PermisoRol" Member="PermisoRol" ThisKey="IdPermiso" OtherKey="IdPermiso" Type="PermisoRol" />
    </Type>
  </Table>
  <Table Name="dbo.PermisoRol" Member="PermisoRol">
    <Type Name="PermisoRol">
      <Column Name="IdPermisoRol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdRol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPermiso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Permiso_PermisoRol" Member="Permiso" ThisKey="IdPermiso" OtherKey="IdPermiso" Type="Permiso" IsForeignKey="true" />
      <Association Name="Rol_PermisoRol" Member="Rol" ThisKey="IdRol" OtherKey="IdRol" Type="Rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Precio" Member="Precio">
    <Type Name="Precio">
      <Column Name="IdPrecio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PrecioAnterior" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PorcentajeVenta" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PrecioPublicado" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="IdProd" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Upc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoInstrumento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdMarca" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdModelo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodProveedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Producto_ProductosxNP" Member="ProductosxNP" ThisKey="IdProd" OtherKey="IdProd" Type="ProductosxNP" />
      <Association Name="Producto_ProductosxOC" Member="ProductosxOC" ThisKey="IdProd" OtherKey="IdProd" Type="ProductosxOC" />
      <Association Name="Marca_Producto" Member="Marca" ThisKey="IdMarca" OtherKey="IdMarca" Type="Marca" IsForeignKey="true" />
      <Association Name="Modelo_Producto" Member="Modelo" ThisKey="IdModelo" OtherKey="IdModelo" Type="Modelo" IsForeignKey="true" />
      <Association Name="Proveedor_Producto" Member="Proveedor" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductosxNP" Member="ProductosxNP">
    <Type Name="ProductosxNP">
      <Column Name="IdProductosxNP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NroPedido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NotaDePedido_ProductosxNP" Member="NotaDePedido" ThisKey="NroPedido" OtherKey="NroPedido" Type="NotaDePedido" IsForeignKey="true" />
      <Association Name="Producto_ProductosxNP" Member="Producto" ThisKey="IdProd" OtherKey="IdProd" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductosxOC" Member="ProductosxOC">
    <Type Name="ProductosxOC">
      <Column Name="IdProductosxOC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NroOrdenCompra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OrdenCompra_ProductosxOC" Member="OrdenCompra" ThisKey="NroOrdenCompra" OtherKey="NroOrdenCompra" Type="OrdenCompra" IsForeignKey="true" />
      <Association Name="Producto_ProductosxOC" Member="Producto" ThisKey="IdProd" OtherKey="IdProd" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedor" Member="Proveedor">
    <Type Name="Proveedor">
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CodProveedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RazonSocial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cuit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Proveedor_OrdenCompra" Member="OrdenCompra" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="OrdenCompra" />
      <Association Name="Proveedor_OrdenPago" Member="OrdenPago" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="OrdenPago" />
      <Association Name="Proveedor_Producto" Member="Producto" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Recibo" Member="Recibo">
    <Type Name="Recibo">
      <Column Name="NroRecibo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CodCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ImporteTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Notas" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NroFactura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cliente_Recibo" Member="Cliente" ThisKey="CodCliente" OtherKey="CodCliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Factura_Recibo" Member="Factura" ThisKey="NroFactura" OtherKey="NroFactura" Type="Factura" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Remito" Member="Remito">
    <Type Name="Remito">
      <Column Name="NroRemito" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NroPedido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NroFactura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notas" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Factura_Remito" Member="Factura" ThisKey="NroFactura" OtherKey="NroFactura" Type="Factura" IsForeignKey="true" />
      <Association Name="NotaDePedido_Remito" Member="NotaDePedido" ThisKey="NroPedido" OtherKey="NroPedido" Type="NotaDePedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rol" Member="Rol">
    <Type Name="Rol">
      <Column Name="IdRol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoRol" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Rol_PermisoRol" Member="PermisoRol" ThisKey="IdRol" OtherKey="IdRol" Type="PermisoRol" />
      <Association Name="Rol_UsuarioRol" Member="UsuarioRol" ThisKey="IdRol" OtherKey="IdRol" Type="UsuarioRol" />
    </Type>
  </Table>
  <Table Name="dbo.Traduccion" Member="Traduccion">
    <Type Name="Traduccion">
      <Column Name="IdTraduccion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdIdioma" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdControl" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ControlSistema_Traduccion" Member="ControlSistema" ThisKey="IdControl" OtherKey="IdControl" Type="ControlSistema" IsForeignKey="true" />
      <Association Name="Idioma_Traduccion" Member="Idioma" ThisKey="IdIdioma" OtherKey="IdIdioma" Type="Idioma" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usuario" Member="Usuario1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdIdioma" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dni" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Usuario_UsuarioRol" Member="UsuarioRol" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="UsuarioRol" />
      <Association Name="Idioma_Usuario" Member="Idioma" ThisKey="IdIdioma" OtherKey="IdIdioma" Type="Idioma" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioRol" Member="UsuarioRol">
    <Type Name="UsuarioRol">
      <Column Name="IdUsuarioRol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdRol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rol_UsuarioRol" Member="Rol" ThisKey="IdRol" OtherKey="IdRol" Type="Rol" IsForeignKey="true" />
      <Association Name="Usuario_UsuarioRol" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.ActualizarMarca" Method="ActualizarMarca">
    <Parameter Name="IdMarca" Parameter="idMarca" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarModelo" Method="ActualizarModelo">
    <Parameter Name="IdModelo" Parameter="idModelo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarPermiso" Method="ActualizarPermiso">
    <Parameter Name="IdPermiso" Parameter="idPermiso" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoPermiso" Parameter="tipoPermiso" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarPrecio" Method="ActualizarPrecio">
    <Parameter Name="IdPrecio" Parameter="idPrecio" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Double" DbType="Float" />
    <Parameter Name="PrecioAnterior" Parameter="precioAnterior" Type="System.Double" DbType="Float" />
    <Parameter Name="PorcentajeVenta" Parameter="porcentajeVenta" Type="System.Double" DbType="Float" />
    <Parameter Name="PrecioPublicado" Parameter="precioPublicado" Type="System.Double" DbType="Float" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarProducto" Method="ActualizarProducto">
    <Parameter Name="IdProd" Parameter="idProd" Type="System.Int32" DbType="Int" />
    <Parameter Name="Upc" Parameter="upc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoInstrumento" Parameter="tipoInstrumento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdMarca" Parameter="idMarca" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdModelo" Parameter="idModelo" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodProveedor" Parameter="codProveedor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarProveedor" Method="ActualizarProveedor">
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodProveedor" Parameter="codProveedor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NombreEmpresa" Parameter="nombreEmpresa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RazonSocial" Parameter="razonSocial" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cuit" Parameter="cuit" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarRol" Method="ActualizarRol">
    <Parameter Name="IdRol" Parameter="idRol" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoRol" Parameter="tipoRol" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizarUsuario" Method="ActualizarUsuario">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdIdioma" Parameter="idIdioma" Type="System.Int32" DbType="Int" />
    <Parameter Name="Dni" Parameter="dni" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AnularRecibo" Method="AnularRecibo">
    <Parameter Name="NroRecibo" Parameter="nroRecibo" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AnularRemito" Method="AnularRemito">
    <Parameter Name="NroRemito" Parameter="nroRemito" Type="System.Int32" DbType="Int" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarMarca" Method="EliminarMarca">
    <Parameter Name="IdMarca" Parameter="idMarca" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarModelo" Method="EliminarModelo">
    <Parameter Name="IdModelo" Parameter="idModelo" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarPermiso" Method="EliminarPermiso">
    <Parameter Name="IdPermiso" Parameter="idPermiso" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarPrecio" Method="EliminarPrecio">
    <Parameter Name="IdPrecio" Parameter="idPrecio" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarProducto" Method="EliminarProducto">
    <Parameter Name="IdProd" Parameter="idProd" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarProveedor" Method="EliminarProveedor">
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarRol" Method="EliminarRol">
    <Parameter Name="IdRol" Parameter="idRol" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminarUsuario" Method="EliminarUsuario">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GenerarRecibo" Method="GenerarRecibo">
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CodCliente" Parameter="codCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ImporteTotal" Parameter="importeTotal" Type="System.Double" DbType="Float" />
    <Parameter Name="Notas" Parameter="notas" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NroFactura" Parameter="nroFactura" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarMarca" Method="InsertarMarca">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarModelo" Method="InsertarModelo">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarPermiso" Method="InsertarPermiso">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoPermiso" Parameter="tipoPermiso" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarPrecio" Method="InsertarPrecio">
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Double" DbType="Float" />
    <Parameter Name="PrecioAnterior" Parameter="precioAnterior" Type="System.Double" DbType="Float" />
    <Parameter Name="PorcentajeVenta" Parameter="porcentajeVenta" Type="System.Double" DbType="Float" />
    <Parameter Name="PrecioPublicado" Parameter="precioPublicado" Type="System.Double" DbType="Float" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarProducto" Method="InsertarProducto">
    <Parameter Name="Upc" Parameter="upc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoInstrumento" Parameter="tipoInstrumento" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdMarca" Parameter="idMarca" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdModelo" Parameter="idModelo" Type="System.Int32" DbType="Int" />
    <Parameter Name="CodProveedor" Parameter="codProveedor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Color" Parameter="color" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarProveedor" Method="InsertarProveedor">
    <Parameter Name="CodProveedor" Parameter="codProveedor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NombreEmpresa" Parameter="nombreEmpresa" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RazonSocial" Parameter="razonSocial" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripion" Parameter="descripion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cuit" Parameter="cuit" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarRemito" Method="InsertarRemito">
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NroPedido" Parameter="nroPedido" Type="System.Int32" DbType="Int" />
    <Parameter Name="NroFactura" Parameter="nroFactura" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Notas" Parameter="notas" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarRol" Method="InsertarRol">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TipoRol" Parameter="tipoRol" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarUsuario" Method="InsertarUsuario">
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido" Parameter="apellido" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdIdioma" Parameter="idIdioma" Type="System.Int32" DbType="Int" />
    <Parameter Name="Dni" Parameter="dni" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>